version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-buster

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: gem install bundler -v 2.0.2

      - run:
          name: install dependencies
          command: |
            bundle install

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec

      # run rubocop!
      - run:
          name: run rubocop
          command: |
            bundle exec rubocop
